packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - bcrypt
